#!/bin/env bash

_i()
{
    winman="i3s"

    xlist=(
        "eDP-1"
        "DP-2"
        "DP-2-2"
        "DP-2-3"
        "DP-2-3"
        "DP-3"
        "DP2-2"
        "DP2-3"
        "HDMI-1"
        "HDMI-2"
        "HDMI1"
        "HDMI2"
    )

    xlist_connected="$(xrandr | grep " connected" | cut -d" " -f1)"
}

init_defs()
{
    # singles & bases
  
    e1=(     "--output"    "eDP-1"  "--auto" )
    e1p=(    "${e1[@]}"    "--primary" )
    d_1=(    "--output"    "DP-1"   "--auto" )
    d_1p=(   "${d_1[@]}"   "--primary" )
    d_1pr=(  "${d_1[@]}"   "--rotate left")
    d_1r=(   "${d_1[@]}"   "--rotate left")
    d_2=(    "--output"    "DP-2"   "--auto" )
    d_2p=(   "${d_2[@]}"   "--primary" )
    d_22=(   "--output"    "DP-2-2" "--auto" )
    d_22p=(  "${d_22[@]}"  "--primary" )
    d_22r=(  "${d_22[@]}"  "--rotate right" )
    d_22pr=( "${d_22p[@]}" "--rotate right" )

    d_23=(   "--output"   "DP-2-3" "--auto" )
    d_23p=(  "${d_23[@]}"  "--primary" )
    d_23r=(  "${d_23[@]}"  "--rotate right" )
    d2_1=(   "--output"   "DP2-1"  "--auto" )
    d2_1p=(  "${d2_1[@]}"  "--primary" )
    d2_2=(   "--output"   "DP2-2"  "--auto" )
    d2_2p=(  "${d2_2[@]}"  "--primary" )
    d2_3=(   "--output"   "DP2-3"  "--auto" )
    d2_3p=(  "${d2_3[@]}"  "--primary" )
    h1=(     "--output"   "HDMI-1" "--auto" )
    h1p=(    "${h1[@]}"    "--primary" )
    h2=(     "--output"   "HDMI-2" "--auto" )
    h2p=(    "${h2[@]}"    "--primary" )

    # doubles
  
    #2
    e1p__d_2=(     
        "${e1[@]}"      "--primary"
        "${d_2[@]}"     "--right-of" )
    h1p_e1r=(
        "${h1[@]}"      "--primary"
        "${e1[@]}"      "--right-of")
    #23 -22 - ...  
    d_23__d_22p=(
        "${d_23[@]}"    "--left-of"  "DP-2-2"
        "${d_22[@]}"    "--primary")
    d_23p__d_22=(
        "${d_23[@]}"    "--primary"
        "${d_23[@]}"    "--right-of"  "DP-2-3")
    d_23p__d_22r__e1b=(
        "${d_23[@]}"    "--primary"
        "${d_22[@]}"    "--right-of"  "DP-2-3"
        "${e1[@]}"      "--below"     "DP-2-2")
    #22 -23 - ... 
    d_22p__d_23=(  
        "${d_22[@]}"    "--primay"
        "${d_23[@]}"    "--right-of")
    #22 -1 - ... 
    d_22r__d_1p=(
        "${d_22r[@]}"   "--left-of"  "DP-1"
        "${d_1[@]}"     "--primary")
    d_22r__d_1p__d_22r=(
        "${d_22r__d_1p[@]}"
        "${d_23r[@]}"  "--right-of" "DP-1")
    #1 -23 - .... 
    d_1pr__d_23r=(  # 2 rot
        "${d_1r[@]}"    "--primary"
        "${d_23r[@]}"   "--right-of" "DP-1")
    d_1p__d_23rl=(  
        "${d_1[@]}"     "--primary"
        "${d_22r[@]}"   "--right-of" "DP-1" )
}

xoff()      { xrandr --output ${1} --off; }

xoff_lp()
{
    for disp in ${1}
    do 
        xoff ${disp}
    done
}

xoff_lp_all()
{ 
    for disp in ${xlist_connected}
    do
        xoff ${disp}
    done
}

xoff_lp_partial()
{
    for disp in ${xlist_off[@]}
    do
        xoff ${disp}
    done
}

xoff_set_partial()
{
    for i in ${xlist_connected};
    do
        [ -n "$(echo "${@}" | grep " ${i}")" ] \
            || { xlist_off+=("${i}"); }
    done
}

xoff_partial() { xoff_set_partial "${@}"; xoff_lp_partial; }

