#!/bin/env bash

cmd=$1
shift 1

# VARS ######################################

winman="${HOME}/.local/bin/i3s"

xlist=( 
  "eDP-1"
  "DP-2"
  "DP-2-2"
  "DP-2-3"
  "DP-2-3"
  "DP-3"
  "DP2-2"
  "DP2-3"
  "HDMI-1"
  "HDMI-2"
  "HDMI1"
  "HDMI2" )

xlist_connected="$(xrandr | grep " connected" | cut -d" " -f1)"


# BASICS ####################################

_pr_active() { xrandr --listactivemonitors; }

_pr_autor()  { autorandr --current; }

_xresize_wins() { $winman win.resize.all; }

_xfeh_bg()  { feh --bg-max "${HOME}/.local/share/abg/bg.jpg" & }

_xnotify()  { notify-send -i display "x setup:" "autorandr: $(_pr_autor) \nxrandr:\n $(_pr_active)" & }


# xoff

_xoff()     { xrandr --output $1 --off; }

_xoff_lp()  { for disp in $1; do _xoff $disp; done }

_xoff_lp_all() { for disp in $xlist_connected; do _xoff $disp; done }

_xoff_lp_partial() { for disp in ${xlist_off[@]}; do _xoff $disp; done }

_xoff_set_partial() { for i in $xlist_connected; do [ -n "$(echo "$@" | grep " $i")" ] || { xlist_off+=("$i"); }; done }

_xoff_partial() { _xoff_set_partial "$@"; _xoff_lp_partial; }


# reload

_xreload() { # todo: add i3 conditional statement
  _xfeh_bg
  _xnotify
  _xresize_wins ;}


# MODES ##################################

# NOTE: dissapearing modelines previously have been associated with cable issues
#   - Re-attaching the cable restablishes the correct default modelines
#   - Or, try a power off on the dock?

# to generate modeline for eg 1920x1080 @ 60 : 'cvt 1920 1080 60'

_xrm_1920_1080_65() {
	xrandr --newmode "1920x1080_65.00" 188.87  \
			1920 2048 2256 2592  \
			1080 1081 1084 1121 -HSync +Vsync
}

_xrm_1920_1080_60() { #outp="DP-2"
	xrandr --newmode "1920x1080_60.00" 172.80 \
			1920 2040 2248 2576 \
			1080 1081 1084 1118 -HSync +Vsync
}

_xrm_add_dp-2-3() {
  xrandr --addmode DP-2-3 "1920x1080_60.00"
  xrandr --output DP-2-3 --mode "1920x1080_60.00"
}

_xrm_fix() {
  _xrm_1920_1080_60
  _xrm_1920_1080_65
  _xrm_add_dp-2-3 ;}
  
#xrm_add_() { --addmode $outp $reso ;}

# SETUPS ################################

_init_defs() {
  
  # singles base ##############################
  
  e1=(     "--output"    "eDP-1"  "--auto" )
  e1p=(    "${e1[@]}"    "--primary" )
  d_1=(    "--output"    "DP-1"   "--auto" )
  d_1p=(   "${d_1[@]}"   "--primary" )
  d_1pr=(  "${d_1[@]}"   "--rotate left")
  d_1r=(   "${d_1[@]}"   "--rotate left")
  d_2=(    "--output"    "DP-2"   "--auto" )
  d_2p=(   "${d_2[@]}"   "--primary" )
  d_22=(   "--output"    "DP-2-2" "--auto" )
  d_22p=(  "${d_22[@]}"  "--primary" )
  d_22r=(  "${d_22[@]}"  "--rotate right" )
  d_22pr=( "${d_22p[@]}" "--rotate right" )

  d_23=(   "--output"   "DP-2-3" "--auto" )
  d_23p=(  "${d_23[@]}"  "--primary" )
  d_23r=(  "${d_23[@]}"  "--rotate right" )
  d2_1=(   "--output"   "DP2-1"  "--auto" )
  d2_1p=(  "${d2_1[@]}"  "--primary" )
  d2_2=(   "--output"   "DP2-2"  "--auto" )
  d2_2p=(  "${d2_2[@]}"  "--primary" )
  d2_3=(   "--output"   "DP2-3"  "--auto" )
  d2_3p=(  "${d2_3[@]}"  "--primary" )
  h1=(     "--output"   "HDMI-1" "--auto" )
  h1p=(    "${h1[@]}"    "--primary" )
  h2=(     "--output"   "HDMI-2" "--auto" )
  h2p=(    "${h2[@]}"    "--primary" )


  # doubles  ##################################
  
  # _2 ######################################
  e1p__d_2=(     
    "${e1[@]}"      "--primary"
    "${d_2[@]}"     "--right-of" )
  h1p_e1r=(
    "${h1[@]}"      "--primary"
    "${e1[@]}"      "--right-of")
  # _23 - _22 - ...  #######################
  d_23__d_22p=(
    "${d_23[@]}"    "--left-of"  "DP-2-2"
    "${d_22[@]}"    "--primary")
  d_23p__d_22r__e1b=(
    "${d_23[@]}"    "--primary"
    "${d_22[@]}"    "--right-of"  "DP-2-3"
    "${e1[@]}"      "--below"     "DP-2-2")
  # _22 - _23 - ... ######################
  d_22p__d_23=(  
    "${d_22[@]}"    "--primay"
    "${d_23[@]}"    "--right-of")
  # _22 - _1 - ... #######################
  d_22r__d_1p=(
    "${d_22r[@]}"   "--left-of"  "DP-1"
    "${d_1[@]}"     "--primary")
  d_22r__d_1p__d_22r=(
    "${d_22r__d_1p[@]}"
    "${d_23r[@]}"  "--right-of" "DP-1")
  # _1 - _23 - .... ########################
  d_1pr__d_23r=(  # 2 rot
    "${d_1r[@]}"    "--primary"
    "${d_23r[@]}"   "--right-of" "DP-1")
  d_1p__d_23rl=(  
    "${d_1[@]}"     "--primary"
    "${d_22r[@]}"   "--right-of" "DP-1" )
  
} # END ######################################


# CMDS ##################################################

_xcmd_set() {
  _init_defs
  eval "args=(\"\${${1}[@]}\")"
  xcmd="xrandr ${args[@]}";}

_xcmd_exec() { $xcmd; }

_xrra() { # $1 is cmd seq
  _xcmd_set $1
  _xcmd_exec
  _xoff_partial "$xcmd"
  _xreload
}


# Run ####################################

case $cmd in 
	#xrra)        xrra $@ ;;
	#xrrx)        xrrx $@ ;;
	off)         _xrroff ;;
	reload)      _xreload ;;
  xr)          _xrra $@ ;;
  xrm_fix)     _xrm_fix ;;
esac

exit

# archive ################################
xrandr --output VGA-1 --primary --auto --output LVDS-1 --off --auto
xrandr --output LVDS-1 --primary --auto --output VGA-1 --off
