#!/bin/env bash

_i()
{
    winman="i3s"

    xlist=(
        "eDP-1"
        "DP-2"
        "DP-2-2"
        "DP-2-3"
        "DP-2-3"
        "DP-3"
        "DP2-2"
        "DP2-3"
        "HDMI-1"
        "HDMI-2"
        "HDMI1"
        "HDMI2"
    )

    xlist_connected="$(xrandr | grep " connected" | cut -d" " -f1)"
}

pr_active() { xrandr --listactivemonitors; }

pr_autor()  { autorandr --current; }

xsetx()
{
    case ${1} in
        ## performance configs
        a) xset r rate 70 150 ;;
        b) xset r rate 75 150 ;;
        c) xset r rate 80 150 ;;
        d) xset r rate 90 150 ;;
        ## easy
        l) xset r rate 100 100 ;;
        m) xset r rate 120 100 ;;
        n) xset r rate 120 120 ;;
        o) xset r rate 150 90 ;;
        p) xset r rate 200 50 ;;
    esac
}

xsety() { xsetx d & }

xrdbx() { xrdb -I${HOME}/.config .config/X11/xresources & }

fehx()  { feh --no-fehbg --bg-max "${BGX_FEH}" & }

notifx()
{
    notify-send -i display \
        "x setup:" "autorandr: $(pr_autor) \nxrandr:\n $(pr_active)" &
}

# reload

xinix() { . ${XPROFILE} ; }

xiniy()
{
    # todo: add i3 conditional statement
    fehx
    xsety
    notifx
    systemctl --user restart clock.service
}

xreload()
{
    xiniy
    if pgrep i3; then
        ${winman} r # resize wins
    fi
}

# modes

# dissapearing modelines previously have been associated with cable issues
# re-attaching the cable restablishes the correct default modelines
# or try a power off on the dock?

# to generate modeline for eg 1920x1080 @ 60 : 'cvt 1920 1080 60'

xrm_1920_1080_65()
{
    xrandr --newmode "1920x1080_65.00" 188.87  \
         1920 2048 2256 2592  \
         1080 1081 1084 1121 -HSync +Vsync
}

xrm_1920_1080_60()
{
    #outp="DP-2"
    xrandr --newmode "1920x1080_60.00" 172.80 \
         1920 2040 2248 2576 \
         1080 1081 1084 1118 -HSync +Vsync
}

xrm_add_dp-2-3()
{
    xrandr --addmode DP-2-3 "1920x1080_60.00"
    xrandr --output DP-2-3 --mode "1920x1080_60.00"
}

xrm_add_dp-2()
{
    #xrandr --addmode DP-2 "1920x1080_60.00"
    xrandr --addmode DP-2 "1024x768_60.00"
    xrandr --output DP-2 --mode "1024x768_60.00"
}

xrm_fix_2()
{
    xrm_1920_1080_60
    xrm_1920_1080_65
    xrm_add_dp-2-3
}

xrm_fix()
{
    xrm_1920_1080_60
    xrm_1920_1080_65
    xrm_add_dp-2
}
 
#xrm_add_() { --addmode $outp $reso ;}


# cmds

xcmd_set()
{
    init_defs
    eval "args=(\"\${${1}[@]}\")"
    xcmd="xrandr ${args[@]}"
}

xcmd_exec() { ${xcmd}; }

xrra()
{
    xcmd_set ${1}
    xcmd_exec
    xoff_partial "${xcmd}"
    xreload
}

main()
{
    cmd=${1}
    shift 1

    _i

    case ${cmd} in
        #xrra)        xrra $@ ;;
        #xrrx)        xrrx $@ ;;
        o|off)        xrroff ;;
        xset)         xsetx ${1} ;;
        xseta)        xsety ;;
        i|init)       xiniy ;;
        r|reload)     xreload ;;
        x|xr)         xrra ${@} ;;
        f|xrm_fix)    xrm_fix ;;
    esac
}

main "${@}"
